"""add_custom_insight_prompt_to_user_preferences

Revision ID: 67f16afb7b90
Revises: 6dc2e3b0a0b3
Create Date: 2026-05-23 13:41:35.939694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67f16afb7b90'
down_revision: Union[str, None] = '6dc2e3b0a0b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_preferences', sa.Column('custom_insight_prompt', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_preferences', 'custom_insight_prompt')
    # ### end Alembic commands ###
